steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/attendance-system', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/attendance-system']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'attendance-system',
         '--image', 'gcr.io/$PROJECT_ID/attendance-system',
         '--platform', 'managed',
         '--region', 'us-central1',
         '--allow-unauthenticated']
