steps:
# Step to build the main Flask app
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/attendance-system', '.']

# Step to push the main Flask app image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/attendance-system']

# Step to deploy the main Flask app to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'attendance-system',
         '--image', 'gcr.io/$PROJECT_ID/attendance-system',
         '--platform', 'managed',
         '--region', 'us-central1',
         '--allow-unauthenticated']

# Step to deploy the QR generation Cloud Function
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['functions', 'deploy', 'scheduled_qr_generator',
         '--runtime', 'python39',
         '--trigger-topic', 'generate-qr-codes',
         '--entry-point', 'scheduled_qr_generator',
         '--region', 'us-central1',
         '--source', '.',
         '--allow-unauthenticated']
